.shared_config:
  rules:
    on_development_build:
      - if: $CI_COMMIT_BRANCH == 'develop' && ($CI_PIPELINE_SOURCE == 'push' || $CI_PIPELINE_SOURCE == 'web')
        when: on_success
    on_development_deploy:
      - if: $CI_COMMIT_BRANCH == 'develop' && ($CI_PIPELINE_SOURCE == 'push' || $CI_PIPELINE_SOURCE == 'web')
        when: on_success

    on_production_build:
      - if: $CI_COMMIT_TAG =~ /v[0-9]+\.[0-9]+\.[0-9]+/ && ($CI_PIPELINE_SOURCE == 'push' || $CI_PIPELINE_SOURCE == 'web')
        when: on_success
    on_production_deploy:
      - if: $CI_COMMIT_TAG =~ /v[0-9]+\.[0-9]+\.[0-9]+/ && ($CI_PIPELINE_SOURCE == 'push' || $CI_PIPELINE_SOURCE == 'web')
        when: on_success

  cache:
    npm:
      key: npm-cache
      paths:
        - .npm/
      when: on_success
      policy: pull-push
    node_modules:
      key:
        files:
          - package-lock.json
        prefix: node_modules
      paths:
        - node_modules/
      policy: pull
